/* This file is auto-generated by SST. Do not edit. */
/* tslint:disable */
/* eslint-disable */
/* deno-fmt-ignore-file */
/* biome-ignore-all lint: auto-generated */

declare module "sst" {
  export interface Resource {
    "AnthropicApiKey": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "Database": {
      "clusterArn": string
      "database": string
      "host": string
      "password": string
      "port": number
      "secretArn": string
      "type": "sst.aws.Postgres"
      "username": string
    }
    "DatabasePassword": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "DocumentProcessing": {
      "type": "sst.aws.Queue"
      "url": string
    }
    "Documents": {
      "name": string
      "type": "sst.aws.Bucket"
    }
    "NextAuthSecret": {
      "type": "sst.sst.Secret"
      "value": string
    }
    "WorkflowExecution": {
      "type": "sst.aws.Queue"
      "url": string
    }
  }
}

import "sst"
export {}