# Automatically generated by SST
# pylint: disable=all
# ruff: noqa
from typing import Any

class Resource:
    class AnthropicApiKey:
        type: str
        value: str
    class Api:
        service: str
        type: str
    class App:
        name: str
        stage: str
    class Database:
        database: str
        host: str
        password: str
        port: float
        type: str
        username: str
    class DatabasePassword:
        type: str
        value: str
    class DocumentProcessing:
        type: str
        url: str
    class Documents:
        name: str
        type: str
    class EluvenVpc:
        type: str
    class Frontend:
        type: str
        url: str
    class NextAuthSecret:
        type: str
        value: str
    class WorkflowExecution:
        type: str
        url: str

